# Define folder paths
$sourceFolder = "src"
$imgOutputFolder = "preview_images"
$stlOutputFolder = "stls"
$markdownFile = "Readme.md"
$readmeFile = ".readme.md"

# Create output folder if it doesn't exist
if (-not (Test-Path $imgOutputFolder)) {
    New-Item -ItemType Directory -Path $imgOutputFolder | Out-Null
}
if (-not (Test-Path $stlOutputFolder)) {
    New-Item -ItemType Directory -Path $stlOutputFolder | Out-Null
}

# Clear existing content of markdown file
Clear-Content $markdownFile

Get-Content -Path $readmeFile | Add-Content -Path $markdownFile

Add-Content -Path $markdownFile -Value "## Autogenerated Overview"

Add-Content -Path $markdownFile -Value "| Preview | SCAD | STL |" 
Add-Content -Path $markdownFile -Value "| --- | --- | --- |" 

# Array to store all process objects
$processes = @()

# Iterate over .scad files
$scadFiles = Get-ChildItem -Path $sourceFolder -Filter "*.scad" -File
foreach ($file in $scadFiles) {
    $pngFileName = Join-Path -Path $imgOutputFolder -ChildPath ($file.BaseName + ".png")
    $stlFileName = Join-Path -Path $stlOutputFolder -ChildPath ($file.BaseName + ".stl")
    

    $params = @{
        FilePath = "C:\Program Files\OpenSCAD\openscad.exe"
        ArgumentList = "-o `"$pngFileName`" `"$($file.FullName)`" --render --imgsize 768,768"
    }
    Write-Host "Generating PNG for `"$($file)`""
    $process = Start-Process @params -PassThru
    $processes += $process
    

    $params = @{
        FilePath = "C:\Program Files\OpenSCAD\openscad.exe"
        ArgumentList = "-D fn=512 -o `"$stlFileName`" `"$($file.FullName)`""
    }
    Write-Host "Generating STL for `"$($file)`""
    $process = Start-Process @params -PassThru
    $processes += $process

    # Convert file paths to Unix style
    $unixPngFileName = $pngFileName -replace '\\', '/'
    $unixSrcPath = $sourceFolder -replace '\\', '/'
    $stlOutputFolderUnix = $stlOutputFolder -replace '\\', '/'
    $stlFileName = "$stlOutputFolderUnix/$($file.BaseName).stl"

    # Append image link to markdown file with file paths in Unix style
    Add-Content -Path $markdownFile -Value "| ![$($file.BaseName)]($unixPngFileName) | [SCAD File]($unixSrcPath/$($file.Name)) | [STL File]($stlFileName) |"
}

# Check if any processes are still running
do {
    $runningProcesses = $processes | Where-Object { -not $_.HasExited }
    Start-Sleep -Seconds 5
} while ($runningProcesses.Count -gt 0)